config/routes.rb
Rails.application.routes.draw do
  get 'reports', to: 'reports#index'
  
  get 'exportar', to: 'reports#exportar'
  post 'exportar', to: 'reports#exportar'

  get 'calendar', to:'calendar#index'

  resources :registers
  resources :users
  resources :people
  resources :roles

  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  post 'users/habilitar'
  post 'users/deshabilitar'
  post 'registers/query'
  get 'descargar', to: 'registers#descargar'
  
  get 'menu/index'
  root 'home#index'

  get '/exportar.xml', :to => 'reports#exportar', :defaults => {:format => 'xml'}

  
  get "reports/query"
  post "reports/query"
  
 

  match '/exportar.csv' => 'reports#exportar', via: :get, defaults: { format: :csv }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :user

  def self.filtrar(user, range)
    Register.where(  user_id: user, date: range.all_month )
  end

  def self.to_csv
    CSV.generate() do |csv|
      csv << ["ID", "Empleado", "Fecha", "Hora de entrada", "Hora de salida", "Total de horas de trabajo"]
      all.each do |r|
        csv << [r.id, "#{r.user.person.name}" + " " + "#{r.user.person.paternalLastName}" +  " " + "#{r.user.person.maternalLastName}" , r.date, r.hour_start.strftime("%I:%M %p") , r.hour_end.strftime("%I:%M %p") , r.total_hours ]
      end
    end
  end

  
  #def self.to_csv
  #  CSV.generate() do |csv|
  #    csv << column_names
  #    all.each do |register|
  #      csv << register.attributes.values_at(*column_names)
  #    end
  #  end
  #end
  
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: %i[ show edit update destroy ]

  # GET /registers or /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1 or /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
    @session = session[:user_id]
    @register.id = @session
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers or /registers.json
  def create
    #FECHA
    @day = register_params["date(1i)"].to_i 
    @month = register_params["date(2i)"].to_i
    @year = register_params["date(3i)"].to_i
    @start_date = Date.new(@day, @month, @year)
    
    #HORA 
    @hour = register_params["hour(4i)"].to_i 
    @seg = register_params["hour(5i)"].to_i
    @start_time = Time.new(@day,@month,@year, @hour, @seg, 0)
    
    
    if register_params[:tipo] == "E"
      @register = Register.new

      @register.date = @start_date
      @register.hour_start = @start_time
      @register.hour_end = nil
      @register.total_hours = nil
      @register.user_id = register_params[:user_id]

    else
      puts "SALIDA"
      #Agregar llenar la hora en el hour_end

      @registers = Register.joins(:user).where(  users: {id: register_params[:user_id]} , registers:{date: @start_date.all_day})
      
      if @registers.length == 1

        @registers.each do |item|
          @register = Register.find(item.id)
          @register.hour_end = @start_time
          @register.hour_start  = item.hour_start
          @register.total_hours = (Time.parse(@register.hour_end.strftime("%Y-%m-%d %H:%M")) - Time.parse(@register.hour_start.strftime("%Y-%m-%d %H:%M")))/3600

        end
      else
        puts "NO HAY DATOS"
      end

    end
    
    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: "Register was successfully created."}
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1 or /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: "Register was successfully updated." }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1 or /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: "Register was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def register_params
      params.require(:register).permit(:tipo,:hour,:date , :user_id)
      #params.require(:register).permit(:tipo, :hour,  :date, :hour_start, :hour_end, :total_hours, :user_id)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_with(model: register, remote: true, class:"formu p-3 rounded mx-auto my-5") do |form| %>
  <% if register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :tipo , params[:tipo], class:"form-label my-1 d-flex"%>
    <div class="form-check d-flex align-items-center">
      <%= form.radio_button :tipo, 'E', class:"form-check-input", id:"flexRadioDefault2" %>
      <label class="form-check-label mx-2" for="flexRadioDefault2">
        Entrada
      </label>
    </div>
     <div class="form-check d-flex align-items-center">
      <%= form.radio_button :tipo, 'S', class:"form-check-input", id:"flexRadioDefault3" %>
      <label class="form-check-label mx-2" for="flexRadioDefault3">
        Salida
      </label>
    </div>

  </div>


  <div class="field mb-3">
    <%= form.label class:"form-label my-1" do%>
      Fecha
    <% end  %>
    <div class="d-flex inp">
      <%= form.date_select :date , order: [:day, :month, :year], start_year: 2021  %>
    </div>
  </div>

  
  <div class="field mb-3">
    <%= form.label class:"form-label my-1" do%>
      Hora
    <% end  %>
    <div class="d-flex inp align-items-center">
      <%= form.time_select :hour %>
    </div>
  </div>

  <div class="field mb-3">
    <%= form.text_field :user_id, :value=> @session, class:"form-control", type:'hidden' %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-success w-100"%>
  </div>
  
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form', register: @register %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Lista de Registros</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to new_register_path, class: "btn btn-light text-center mx-2 text-black" do %>
         <i class="bi bi-plus-lg"></i>
          Nuevo
        <% end %>
        <a href="/menu" class="btn btn-dark text-white" title="Atrás"> 
          <i class="bi bi-arrow-90deg-left"></i>
        </a> 
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
    <div class="table-responsive bg-white p-3 rounded-3">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Fecha</th>
            <th>Hora de entrada</th>
            <th>Hora de salida</th>
            <th>Total de horas</th>
            <th>Empleado</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @registers.each do |register| %>

            <% if current_user.role.id == 1 %>
              <!--ROL: ADMIN-->
              <tr>
                <td><%= register.id %></td>
                <td><%= register.date %></td>
                <td><%= register.hour_start.strftime("%I:%M %p") %></td>
                <td><%= register.hour_end.strftime("%I:%M %p") %></td>
                <td>
                  <%= register.user.person.name %>
                  <%= register.user.person.paternalLastName %>
                  <%= register.user.person.maternalLastName %>
                </td>
                <td>
                  <%= link_to register, class: "btn btn-success text-white" do %>
                    <i class="bi bi-eye-fill"></i>
                  <%  end  %>
                  
                </td>
                
              </tr>
            <% else %>
              <!--ROL: EMPLEADO-->

              <% if register.user.id == current_user.id %>
                <tr>
                  <td><%= register.id %></td>
                  <td><%= register.date %></td>
                  <td><%= register.hour_start.strftime("%I:%M %p") %></td>
                  <td><%= register.hour_end == nil ? '---':register.hour_end.strftime("%I:%M %p")%></td>
                  <td><%= register.total_hours == nil ? '---':register.total_hours%></td>
                  <td>
                    <%= register.user.person.name %>
                    <%= register.user.person.paternalLastName %>
                    <%= register.user.person.maternalLastName %>
                  </td>
                  <td>
                    <%= link_to register, class: "btn btn-success text-white" do %>
                      <i class="bi bi-pencil-square"></i>
                    <%  end  %>
                  </td>
                  <td>
                    <%= link_to edit_register_path(register), class: "btn btn-warning" do%>
                      <i class="bi bi-eye-fill"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to register,class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="bi bi-x-square"></i>
                    <% end %>
                  </td>
                 
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/registers/new.html.erb
<div class="list">
    <div class="header">
        <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
            <h1 class="text-white">Nuevo Registro</h1>
            <div class="d-flex justify-content-around">
                <%= link_to registers_path, class:"btn btn-dark text-white", title:"Atrás" do %>
                    <i class="bi bi-arrow-90deg-left"></i>
                <% end %>
            </div>
        </div>
    </div>
    <div class="container mx-auto py-4">
        <%= render 'form', register: @register, class:"form-reg" %>
    </div>
</div>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @register.date %>
</p>

<p>
  <strong>Hour start:</strong>
  <%= @register.hour_start %>
</p>

<p>
  <strong>Hour end:</strong>
  <%= @register.hour_end %>
</p>

<p>
  <strong>Total hours:</strong>
  <%= @register.total_hours %>
</p>

<p>
  <strong>User:</strong>
  <%= @register.user %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>