config/routes.rb
Rails.application.routes.draw do
  get 'reports', to: 'reports#index'
  
  get 'exportar', to: 'reports#exportar'
  post 'exportar', to: 'reports#exportar'

  get 'calendar', to:'calendar#index'

  resources :registers
  resources :users
  resources :people
  resources :roles

  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  post 'users/habilitar'
  post 'users/deshabilitar'
  post 'registers/query'
  get 'descargar', to: 'registers#descargar'
  
  get 'menu/index'
  root 'home#index'

  get '/exportar.xml', :to => 'reports#exportar', :defaults => {:format => 'xml'}

  
  get "reports/query"
  post "reports/query"
  
 

  match '/exportar.csv' => 'reports#exportar', via: :get, defaults: { format: :csv }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
    has_one :user


    def full_name
        "#{self.try(:name)} #{self.try(:paternalLastName)} #{self.try(:maternalLastName)}"
    end
    
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :paternalLastName, :maternalLastName)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :paternalLastName %>
    <%= form.text_field :paternalLastName %>
  </div>

  <div class="field">
    <%= form.label :maternalLastName %>
    <%= form.text_field :maternalLastName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Lista de Empleados</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to new_person_path, class: "btn btn-light text-center mx-2 text-black" do %>
         <i class="bi bi-plus-lg"></i>
          Nuevo
        <% end %>
        <a href="/menu" class="btn btn-dark text-white" title="Atrás"> 
          <i class="bi bi-arrow-90deg-left"></i>
        </a> 
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
    <div class="table-responsive bg-white p-3 rounded-3">
      <table class="table table-striped table-hover">

        <thead>
          <tr>
            <th>ID</th>
            <th>Empleado</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @people.each do |person| %>
            <tr>
              <td><%= person.id %></td>
              <td><%= person.full_name %></td>
              <td><%= link_to 'Show', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>

      </table>

    </div>
  </div>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Paternallastname:</strong>
  <%= @person.paternalLastName %>
</p>

<p>
  <strong>Maternallastname:</strong>
  <%= @person.maternalLastName %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>