config/routes.rb
Rails.application.routes.draw do
  get 'reports', to: 'reports#index'
  
  get 'exportar', to: 'reports#exportar'
  post 'exportar', to: 'reports#exportar'

  get 'calendar', to:'calendar#index'

  resources :registers
  resources :users
  resources :people
  resources :roles

  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  post 'users/habilitar'
  post 'users/deshabilitar'
  post 'registers/query'
  get 'descargar', to: 'registers#descargar'
  
  get 'menu/index'
  root 'home#index'

  get '/exportar.xml', :to => 'reports#exportar', :defaults => {:format => 'xml'}

  
  get "reports/query"
  post "reports/query"
  
 

  match '/exportar.csv' => 'reports#exportar', via: :get, defaults: { format: :csv }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  belongs_to :person
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def habilitar
    @user = User.find(params[:id])
    @user.update_attribute(:state, true)
    redirect_to users_path
  end
  
  def deshabilitar
    @user = User.find(params[:id])
    @user.update_attribute(:state, false)
    redirect_to users_path
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :state, :role_id, :person_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.text_field :role_id %>
  </div>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.text_field :person_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Lista de Usuarios</h1>
      <div class="d-flex justify-content-around">
        <%= link_to new_user_path(@user), class: "btn btn-light text-center mx-2 text-black" do%>
          <i class="bi bi-plus-lg"></i>
          Nuevo
        <% end %>
        <a href="/menu" class="btn btn-dark text-white" title="Atrás"> 
          <i class="bi bi-arrow-90deg-left"></i>
        </a> 
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
      
    <p id="notice"><%= notice %></p>
    <div class="table-responsive bg-white p-3 rounded-3">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre de usuario</th>
            <th>Estado</th>
            <th>Rol</th>
            <th>Empleado</th>
            <th colspan="4"></th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.username %></td>
              <td><%= user.state ? 'Activo':'Inactivo'   %></td>
              <td><%= user.role.description %></td>
              <td><%= user.person.name%> <%= user.person.paternalLastName%> <%= user.person.maternalLastName%> </td>
              <td>
                <%= link_to user, class: "btn btn-success text-white" do %>
                  <i class="bi bi-eye-fill"></i>
                <% end %>
              </td>
              <td>
                <%= link_to edit_user_path(user) , class: "btn btn-warning" do%>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
              </td>
              <td>
                <%= link_to user,class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Are you sure?' } do%>
                      <i class="bi bi-x-square"></i>
                <% end%>
              
              </td>

              <% if user.state %>

              <td>
                  <%= link_to users_deshabilitar_path(:id => user.id), method: :post, class: "btn btn-dark text-white", title:"Inabilitar" do%>
                    <i class="bi bi-stop-circle"></i>
                  <% end %>

                </td>
              <% else %>
                <td>
                  <%= link_to users_habilitar_path(:id => user.id), method: :post,  class: "btn btn-info text-dark", title:"Habilitar" do%>
                    <i class="bi bi-play-circle"></i>
                  <% end %>
                </td>
              <% end %>

              <td>
                <%= link_to calendar_path(:id => user.id),class: "btn btn-primary text-white", title:"Calendario" do %>
                  <i class="bi bi-calendar-fill"></i>
                <% end %>
              </td>
            

            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
    
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Person:</strong>
  <%= @user.person %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>