config/routes.rb
Rails.application.routes.draw do
  get 'reports', to: 'reports#index'
  
  get 'exportar', to: 'reports#exportar'
  post 'exportar', to: 'reports#exportar'

  get 'calendar', to:'calendar#index'

  resources :registers
  resources :users
  resources :people
  resources :roles

  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  post 'users/habilitar'
  post 'users/deshabilitar'
  post 'registers/query'
  get 'descargar', to: 'registers#descargar'
  
  get 'menu/index'
  root 'home#index'

  get '/exportar.xml', :to => 'reports#exportar', :defaults => {:format => 'xml'}

  
  get "reports/query"
  post "reports/query"
  
 

  match '/exportar.csv' => 'reports#exportar', via: :get, defaults: { format: :csv }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Lista de Roles</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to new_role_path, class: "btn btn-light text-center mx-2 text-black" do %>
         <i class="bi bi-plus-lg"></i>
          Nuevo
        <% end %>
        <a href="/menu" class="btn btn-dark text-white" title="Atrás"> 
          <i class="bi bi-arrow-90deg-left"></i>
        </a> 
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
    <div class="table-responsive bg-white p-3 rounded-3">
      <table class="table table-striped table-hover">

          <thead>
            <tr>
              <th>ID</th>
              <th>Descripción</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @roles.each do |role| %>
              <tr>
                <td><%= role.id %></td>
                <td><%= role.description %></td>
                <td><%= link_to 'Show', role %></td>
                <td><%= link_to 'Edit', edit_role_path(role) %></td>
                <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>

      </table>

    </div>
  </div>
</div>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>